## 
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories:
    - "/gui"
    - "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "(deps) "
    groups:
      game-dependencies:
        applies-to: version-updates
        patterns:
          - "@citizenfx*"
          - "@nativewrappers*"
          - "@communityox/ox_lib"
      main-dependencies:
        applies-to: version-updates
        patterns:
          - "typescript*"
          - "esbuild*"
          - "vue"
          - "vue-router"
          - "fast-glob"
          - "eslint*"
          - "vite"
          - "@vitejs/plugin-vue"
    labels:
      - "dependencies"
